version: '3'
services:
  redis:
    image: 'redis:6.0-rc-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  rails:
    depends_on:
      - redis
    container_name: backend 
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
  vue:
    depends_on:
      - redis
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn dev --host '0.0.0.0' --port '8080'
    ports:
      - '8080:8080'  
